### ISSUE TITLE
Tab key no longer autocompletes

### ISSUE THREAD

**Issue by ylansegal** [rev087/fancy-new-file#21]
Pressing the `tab` key no longer autocompletes the path typed. Instead, pressing `tab` changes the focus to the open file on top, without closing the fancy-new-file view. 

Let me know if you need more information.

**Comment by Trudko** [comment]
@ylansegal Hi, you may try my fork of this package https://atom.io/packages/advanced-new-file. I think I fixed this issue. I found issue that tab worked only on first time, if you open the package for second time it didn't. If your problem still won't be fixed please open issue in my package repo.

**Comment by ylansegal** [comment]
@Trudko: Thank you: It looks like your fork works well. At this time, I uninstalled fancy-new-file in favor of advanced-new-file, so I will close this ticket.
