### ISSUE TITLE
Atom packages page still old version 0.7

### ISSUE THREAD

**Issue by smonv** [rev087/fancy-new-file#22]
I installed this packages from apm but it still old version 0.7. Can you update this on atom packages page?

**Comment by Trudko** [comment]
@tthanh you might take a look at new (my) fork of this package advanced-new-file. Fancy new file seems to be inactive so I have forked it.

**Comment by tthanh** [comment]
@Trudko 
thank you for suggest me, i'll install your package

**Comment by Trudko** [comment]
@tthanh my pleasure, package is still in development so if you find any problems please create an issue.
