### ISSUE TITLE
Hitting tab for autocomplete exits new file creation

### ISSUE THREAD

**Issue by cpalafox** [rev087/fancy-new-file#24]
Sometimes when I'm trying to use the plugin, it crashes and afterwards I'm no longer able to use the autocomplete functionality, pressing Tab will go outside the file name modal.

**Comment by Trudko** [comment]
hi @cpalafox, please download advanced-new-file which is fork of this repo I've made. If you look at issues and commits it seems that author has abandoned the project. If you have problem with my package please create the issue and provide some additional information there(atom version, os, some error message if there is some) thanks.
