### ISSUE TITLE
List as deprecated in favor of https://github.com/Trudko/advanced-new-file

### ISSUE THREAD

**Issue by ProLoser** [rev087/fancy-new-file#30]
It would be cool to have everyone using the same project and move people over to @trudko's project.

**Comment by rev087** [comment]
I agree @ProLoser, I've been wanting to update this project for a very long time, but I just kept pushing it for later. Now that we have a good alternative, I'll simply point people to @trudko's.

I'll update the README.

**Comment by ProLoser** [comment]
And project description and the name / description in the atom package list if you don't mind :)

**Comment by rev087** [comment]
Trying to remember how to! It's been that long =/
